name: Google News to Discord
on:
  rss:
    url: "https://news.google.com/rss/search?q=%ED%8E%B8%EB%91%90%ED%86%B5&hl=ko&gl=KR&ceid=KR:ko"

jobs:
  discord:
    runs-on: ubuntu-latest
    name: Send a message to discord
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_NEWS }} \
          -H "Content-Type: application/json" \
          -d '{
            "username": "${{ secrets.DISCORD_USERNAME_NEWS }}",
            "avatar_url": "${{ secrets.DISCORD_AVATAR_NEWS }}",
            "content": "**${{ on.rss.outputs.title }}**\n${{ on.rss.outputs.link }}\n\n>>> ${{ on.rss.outputs.contentSnippet }}"
          }'
